folio-org/mod-users

- pom.xml
fixes https://issues.folio.org/browse/DMOD-143
> DMOD-143: rmb 3.0.0

- src/test/java/org/folio/moduserstest/RestVerticleTest.java
On my laptop build fails because embedded postgres takes more than 2 minutes to load.
> fix timeout and package name

- src/main/resources/template_delete_tenant.sql
> Fix drop role in template_delete_tenant.sql

- ramls/examples/group.sample
- ramls/examples/groups.sample
- ramls/groups.raml
- ramls/schemas/usergroup.json
- ramls/schemas/usergroups.json
Add missing content for ramls/examples/groups.sample
Fix whitepsace
> DMOD-117 eslint raml 2

- pom.xml
- src/test/java/org/folio/moduserstest/RestVerticleIT.java
- src/test/resources/postgres-conf.json
use maven integration test phase and PostgresRunner
> DMOD-200 avoid multiple starts of embedded postgres

- pom.xml
- src/test/java/org/folio/moduserstest/RestVerticleTest.java
- src/test/resources/postgres-conf.json
This reverts commit c5467dd0bcdac54f1130e7d394957e10133f2ba8, reversing
changes made to 15f72bab25592651b52282a2b000651cda0b99d9.
> FOLIO-532 Fix java run bug - reverting the merge commit

- pom.xml
Use RMB 12.1.0 which fixes RMB-23
> Fix MODUSERS-11 mvn install fails at random

- src/main/java/org/folio/rest/impl/AddressTypeAPI.java
- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/main/resources/template_create_tenant.sql
- src/test/java/org/folio/moduserstest/RestVerticleIT.java
Adds address type crud to mod-users
> Add address crud

- ModuleDescriptor.json
Reported by Chason Luis(lcx) on Slack #support, thanks!
> fix syntax error in ModuleDescriptor

- src/main/java/org/folio/rest/impl/AddressTypeAPI.java
- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/test/java/org/folio/moduserstest/RestVerticleIT.java
* Remove trailing whitespace
* Remove license header, was IDE default
> FOLIO-351 tidy 2

- Jenkinsfile
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/rest/impl/ProxiesForAPI.java
- src/test/java/org/folio/moduserstest/RestVerticleIT.java
Whitespace.
Remove IDE default license header.
> FOLIO-351 tidy 3

- NEWS.md
The raml-util was already updated yesterday as part of pull #52
> MODUSERS-58: Add news item

- pom.xml
- reference-data/import.sh
- src/main/java/org/folio/rest/impl/UserGroupAPI.java
- src/test/java/org/folio/moduserstest/RestVerticleIT.java
> FOLIO-351 tidy 4

- pom.xml
- src/main/java/org/folio/rest/impl/UserExpiryImpl.java
- src/main/java/org/folio/rest/utils/ExpirationTool.java
- src/test/java/org/folio/moduserstest/RestVerticleIT.java
> FOLIO-351 tidy 6

- src/main/java/org/folio/rest/impl/AddressTypeAPI.java
- src/main/java/org/folio/rest/impl/UserGroupAPI.java
- src/main/java/org/folio/rest/impl/UsersAPI.java
Trigger rebuild with new apidocs configuration for ramls rearrangement.
whitespace changes only
> FOLIO-903 new apidocs config

- src/test/java/org/folio/moduserstest/RestVerticleIT.java
to make metadata.createdByUserId optional
> MODUSERS-142: Update raml submodule

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/moduserstest/RestVerticleIT.java
Due to https://issues.folio.org/browse/MODUSERS-146 we would like to introduce custom field for mod-users
* added custom fields as a dependency
* modified Module Descriptor with an interface of the custom fields
* added custom fields table creation in the scripts section
> MODUSERS-146 - Integrate custom fields to mod-users

- ramls/userdata.json
- src/test/java/org/folio/moduserstest/RestVerticleIT.java
Add option to save custom fields user
> MODUSERS-149: Add custom fields to user

- src/main/resources/templates/db_scripts/schema.json
Add a few indexes to speed up the queries generated by mod-users.
> MODUSERS-150: Add some indexes

- src/test/java/org/folio/moduserstest/RestVerticleIT.java
Fix unit tests related to mod-custom-fields
> MODUSERS-154: Fix unit tests related to mod-custom-fields

- descriptors/ModuleDescriptor-template.json
Increase minor Users interface version due to changes in "User Schema":
* "customFields" attr added
> MODUSERS-149 increase users interface version

- descriptors/ModuleDescriptor-template.json
- pom.xml
Make PUT /custom-fields endpoint available
Update version of custom fields to the newest SNAPSHOT version
Add endpoint to ModuleDescriptor
Add permission
> MODUSERS-179: Make PUT /custom-fields endpoint available

- pom.xml
- src/test/java/org/folio/moduserstest/CustomFieldIT.java
- src/test/resources/fields/shortTextField.json
Due to https://issues.folio.org/browse/MODUSERS-183 we need to update the mod-custom-fields version to the newest one.
* updated mod-custom-fields version to newest 1.2.0 version
* adjusted tests
> MODUSERS-183 - Update mod-users to use new version of mod-custom-fields

- pom.xml
update custom-fields version to the latest one
> Updated custom-fields to latest 1.3.0 version

- pom.xml
- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/test/java/org/folio/moduserstest/GroupIT.java
The problem is that test3CrossTableQueries can not work on its own.
It assumes that test2Group has been executed first!! The solution
is obvious: merge them.
> Fix broken tests in GroupIT / getStream MODUSERS-173

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/service/impl/RecordRepository.java
- src/main/java/org/folio/service/impl/RecordRepositoryImpl.java
- src/main/java/org/folio/service/impl/RecordServiceImpl.java
- src/test/java/org/folio/moduserstest/CustomFieldIT.java
- src/test/java/org/folio/moduserstest/RestVerticleIT.java
- src/test/java/org/folio/moduserstest/UserExpiryImplTest.java
- src/test/java/org/folio/rest/impl/CustomFieldRemovalTest.java
- src/test/java/org/folio/rest/impl/CustomFieldStatisticsTest.java
- src/test/resources/fields/multiSelectField.json
Add support of custom field option IDs
* Implement a new method of `RecordService` interface.
* Add tests and code refactoring.
> MODCFIELDS-43: Add support of custom field option IDs

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/service/impl/RecordRepository.java
- src/main/java/org/folio/service/impl/RecordRepositoryImpl.java
- src/main/java/org/folio/service/impl/RecordServiceImpl.java
- src/test/java/org/folio/rest/impl/CustomFieldRemovalTest.java
- src/test/java/org/folio/rest/impl/CustomFieldStatisticsTest.java
- src/test/java/org/folio/rest/impl/CustomFieldTestBase.java
Add support to fetch option usage.
* update module descriptor with a new endpoint
* implement the new method in RecordService
* update RMB to v30.1.0
* refactor and add tests
> MODCFIELDS-46 Provide statistics of options usage

- ramls/examples/user.sample
- ramls/userdata.json
- src/test/java/org/folio/moduserstest/RestVerticleIT.java
Add the ability to save preferred first name on user record.
* Update `userdata.json` definition
* Add test
> MODUSERS-196 Add support of preferred name on user record

- src/main/java/org/folio/service/impl/RecordRepositoryImpl.java
- src/test/java/org/folio/rest/impl/CustomFieldStatisticsTest.java
- src/test/java/org/folio/rest/impl/CustomFieldTestBase.java
Fix incorrect option usage stats when field assigned as array
Update SQL-query in repository
> MODCFIELDS-62 Fix incorrect option usage stats when field assigned as array

- pom.xml
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/moduserstest/CustomFieldIT.java
Update mod-custom-fields and add migration scripts
> MODCFIELDS-56 - Update mod-custom-fields and add migration scripts

- descriptors/ModuleDescriptor-template.json
Increase `users` interface version due to changes:
* `prefferredFirstName` attribute added
* `departments` attribute added
* CRUD endpoints for departments managing added
> MODUSERS-158 increase users interface version

- pom.xml
- src/test/java/org/folio/moduserstest/RestVerticleIT.java
- src/test/java/org/folio/rest/impl/CustomFieldRemovalTest.java
- src/test/java/org/folio/rest/impl/CustomFieldTestBase.java
- src/test/java/org/folio/rest/impl/DepartmentsAPITest.java
- src/test/java/org/folio/rest/impl/UsersAPIIT.java
Upgrading RMB from 30.1.0 to 30.2.7 fixes many bugs.
We need to try it out to see whether it helps fixing
https://issues.folio.org/browse/MODUSERS-213 "current transaction is aborted".
> MODUSERS-220: Upgrade to RMB 30.2.7

- src/main/java/org/folio/rest/impl/DepartmentsAPI.java
- src/main/java/org/folio/rest/impl/ProxiesForAPI.java
- src/main/java/org/folio/rest/impl/UserGroupAPI.java
- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/test/java/org/folio/rest/impl/DepartmentsAPITest.java
- src/test/java/org/folio/rest/impl/UsersAPITest.java
Add error logging and exception catching where it is missing.
> MODUSERS-222: Ensure complete error logging

- pom.xml
Next version after a regular release [should be](https://dev.folio.org/guidelines/release-procedures/#prepare-and-perform-the-source-release) the next appropriate minor version
> Change next version to 17.2.0 MODUSERS-209

- NEWS.md
- pom.xml
Releases changes from https://github.com/folio-org/mod-users/pull/193
> MODUSERS-231: Release mod-users 17.2.1

- NEWS.md
- pom.xml
* Upgraded to RAML Module Builder 31.1.5 (MODUSERS-237)
> MODUSERS-238: Release 17.2.2 with RMB 31.1.5

- pom.xml
In preparation for release, I'm updating dependencies in the POM file from 
snapshot versions to the release versions.  I've already checked
with the team responsible for these modules to confirm that these are the 
release versions the module should be using.
> Updating snapshot versions in POM to release versions

- NEWS.md
I wasn't clear on when in the release this should be done, 
or wether it would be handled automatically at some stage 
of the process, so I didn't put a date on the version in the 
news file.  In future I'll make sure it gets done earlier in the process.
> adding release date

- ramls/userdata.json
- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/test/java/org/folio/moduserstest/GroupIT.java
- src/test/java/org/folio/moduserstest/RestVerticleIT.java
Fix HTTP status code and return a body with good description what
is wrong.
> MODUSERS-262: Validate patronGroup and addressTypeId to be UUID

- src/test/java/org/folio/rest/impl/UsersAPIIT.java
Requested on https://github.com/folio-org/mod-users/pull/207
> MODUSERS-267: Move helper methods to bottom of UsersAPIIT

- NEWS.md
- pom.xml
Needed for database memory fix, RMB v 33.1.1 with RMB-863.
> MODUSERS-271: Release v18.1.1

- ramls/userdata.json
https://issues.folio.org/browse/MODUSERS-119
> MODUSERS-119: Extend /users userdata.json documentation

- README.md
- pom.xml
Upgrade vert.x, service-tools, custom-fields.
> Upgrade to Vert.x 4.3.1, etc MODUSERS-315

- PERSONAL_DATA_DISCOSURE.md
I don't see any code that's caching user data, nor any code that's explicitly logging it.
> MODUSERS-321: Add personal data disclosure form

- src/main/resources/templates/db_scripts/schema.json
- Performing tests for Check-In/ Check-Out with DB read-write split disabled and enabled warnings about search without indexes were observed.
14:40:58 [595944/proxiesfor] [fs09000000] [9eb67301-6f6e-468f-9b1a-6134dc39a684] [mod_users] WARN  CQL2PgJSON           Doing LIKE search without index for proxyfor.jsonb->>'proxyUserId', CQL >>> SQL: proxyUserId == 204e9336-a6b7-41d3-bbf4-4fdab4db964b >>> lower(f_unaccent(proxyfor.jsonb->>'proxyUserId')) LIKE lower(f_unaccent('204e9336-a6b7-41d3-bbf4-4fdab4db964b'))
Resolves: [MODUSERS-345](https://issues.folio.org/browse/MODUSERS-345)
- Changed the type of index to b-tree index since the type of this field is UUID;
- Tested on rancher environment: 
13:54:59 INFO CQL2PgJSON index proxyfor.jsonb->>'proxyUserId' generated SQL CASE WHEN …
> [MODUSERS-345] Update type of index for proxyUserId field

- NEWS.md
Accidentally specified incorrect year in newsfile.
> correcting date in newsfile

- Dockerfile
- Jenkinsfile
- pom.xml
_[MODUSERS-369](https://issues.folio.org/browse/MODUSERS-369) : Update to Java 17 mod-users_
Update the module to Java 17 and identify issues.
https://wiki.folio.org/display/TC/JDK+17+and+Java+17
Changed the java sdk version to 17 wherever applicable
> MODUSERS-369 : Update to Java 17 mod-users

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/event/service/UserTenantService.java
- src/main/java/org/folio/repository/UserTenantRepository.java
- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/test/java/org/folio/rest/impl/UserTenantIT.java
- src/test/java/org/folio/rest/impl/UsersAPIIT.java
[MODUSERS-368](https://issues.folio.org/browse/MODUSERS-368)
> [MODUSERS-368] - Check for username uniqueness across consortium

- ramls/outboxEventLog.json
- ramls/userEvent.json
- ramls/userTenant.json
- ramls/userTenants.raml
- src/main/java/org/folio/event/service/UserEventProducer.java
- src/main/java/org/folio/event/service/UserOutboxService.java
- src/main/java/org/folio/repository/UserTenantRepository.java
- src/main/java/org/folio/rest/impl/UserTenantsAPI.java
- src/main/java/org/folio/service/UsersService.java
- src/main/resources/templates/db_scripts/create_audit_outbox_table.sql
- src/main/resources/templates/db_scripts/update_user_tenants_table.sql
- src/test/java/org/folio/rest/impl/UserTenantIT.java
- src/test/java/org/folio/rest/impl/UsersAPIIT.java
[MODUSERS-377](https://issues.folio.org/browse/MODUSERS-377) - Add externalSystemId, barcode to user-teant for SAML login
> [MODUSERS-377] - Added externalSystemId, barcode to user-tenant

- src/main/java/org/folio/event/service/UserOutboxService.java
- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/test/java/org/folio/rest/impl/UsersAPIConsortiaTest.java
[MODUSERS-384](https://issues.folio.org/browse/MODUSERS-384) 
Added sending delete user event
> [MODUSERS-384] - Send delete user event

- ramls/userTenant.json
- ramls/userdata.json
- src/main/java/org/folio/domain/UserType.java
- src/main/java/org/folio/event/service/UserOutboxService.java
- src/main/java/org/folio/repository/UserTenantRepository.java
- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/main/resources/templates/db_scripts/update_user_tenants_table.sql
- src/test/java/org/folio/rest/impl/UserTenantIT.java
- src/test/java/org/folio/rest/impl/UsersAPIConsortiaTest.java
[MODUSERS-384](https://issues.folio.org/browse/MODUSERS-384)
Added system user type
> [MODUSERS-384] - Added system user type

- src/main/java/org/folio/repository/UserEventsLogRepository.java
- src/main/java/org/folio/service/UsersService.java
- src/test/java/org/folio/moduserstest/UserOutboxProcessIT.java
- src/test/java/org/folio/rest/impl/UsersAPIConsortiaTest.java
https://issues.folio.org/browse/MODUSERS-377
Issues found in this PR were identified using this Karate PR:
https://github.com/folio-org/folio-integration-tests/pull/1074/
> MODUSERS-377. Fix issue with isPersonalDataChanged flag

- NEWS.md
- pom.xml
Poppy release
While it's helpful for reviewers to help identify potential problems, ensuring …
> MODUSERS-390 - Poppy release

- src/main/java/org/folio/event/service/UserTenantService.java
- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/test/java/org/folio/rest/impl/UsersAPIConsortiaTest.java
[MODUSERS-393](https://issues.folio.org/browse/MODUSERS-393) - Make username as required field for staff user type for ECS mode
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
> [MODUSERS-393] - Make username as required field for staff user type for ECS mode

- src/main/java/org/folio/event/service/UserOutboxService.java
- src/main/java/org/folio/rest/impl/UsersAPI.java
[MODUSERS-395](https://issues.folio.org/browse/MODUSERS-395) - Fix transaction behavior with processing outbox logs
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> [MODUSERS-393] - Fix transaction behavior with processing outbox logs

- NEWS.md
- pom.xml
- src/main/java/org/folio/event/service/UserOutboxService.java
- src/main/java/org/folio/event/service/UserTenantService.java
- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/test/java/org/folio/rest/impl/UsersAPIConsortiaTest.java
[mod-users: module release 19.2.1](https://issues.folio.org/browse/MODUSERS-394) - mod-users: module release 19.2.1
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> [MODUSERS-394] - Release v19.2.1

- src/main/java/org/folio/repository/UserTenantRepository.java
- src/test/java/org/folio/rest/impl/UsersAPIConsortiaTest.java
https://issues.folio.org/browse/MODUSERS-408
> MODUSERS-408. Additional fix for case insensitive username check

- NEWS.md
- pom.xml
- src/main/java/org/folio/repository/UserTenantRepository.java
- src/test/java/org/folio/rest/impl/UsersAPIConsortiaTest.java
> [MODUSERS-408] - Release v19.2.2

- src/main/java/org/folio/rest/impl/UserTenantsAPI.java
- src/test/java/org/folio/rest/impl/UserTenantIT.java
[MODUSERS-412](https://issues.folio.org/browse/MODUSERS-412) - Add missed fields to filtering in user tenants endpoint
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> [MODUSERS-412] - Add fields to filtering in user tenants endpoint

- descriptors/ModuleDescriptor-template.json
- ramls/userTenants.raml
- src/main/java/org/folio/event/service/UserTenantService.java
- src/main/java/org/folio/repository/UserTenantRepository.java
- src/main/java/org/folio/rest/impl/UserTenantsAPI.java
- src/test/java/org/folio/rest/impl/UserTenantIT.java
- src/test/java/org/folio/rest/impl/UsersAPIConsortiaTest.java
- src/test/java/org/folio/rest/impl/UsersAPIIT.java
- src/test/java/org/folio/support/http/UserTenantClient.java
https://issues.folio.org/browse/MODUSERS-411
> MODUSERS-408. Forbid request to ECS tenant if it soft deleted

- descriptors/ModuleDescriptor-template.json
- pom.xml
The purpose of this PR is to add missing permissions in the moduleDescriptor for the user to add/edit/delete the custom fields.
Missing permissions added to the correct permission sets.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is …
> MODUSERS-413 - Unable to add custom fields

- descriptors/ModuleDescriptor-template.json
- ramls/users.raml
- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/test/java/org/folio/rest/impl/UsersAPIIT.java
- src/test/java/org/folio/support/http/UserProfilePictureClient.java
The purpose of the jira is to implement https://issues.folio.org/browse/MODUSERS-418
While …
> MODUSERS-418 Update Profile Picture API for Database Storage

- src/main/java/org/folio/event/service/UserTenantService.java
[MODUSERS-421](https://issues.folio.org/browse/MODUSERS-421) - Disable username uniqueness validation for system users in ECS mode
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
> [MODUSERS-421] - Disable username uniqueness validation for system users

- README.md
- ramls/examples/config.sample
- ramls/users.raml
> [MODUSERS-423]- updated README.md

- src/main/java/org/folio/service/storage/ProfilePictureStorage.java
> [MODUSERS-423]- Updated error message.

- NEWS.md
- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/main/java/org/folio/service/storage/ProfilePictureStorage.java
- src/main/java/org/folio/support/UsersApiConstants.java
- src/test/java/org/folio/rest/impl/UsersAPIIT.java
> [MODUSERS-427]- Disabling profile pic functionality for shadow users

- src/main/java/org/folio/service/storage/FolioS3ClientFactory.java
- src/main/java/org/folio/service/storage/ProfilePictureStorage.java
- src/main/java/org/folio/support/ProfilePictureHelper.java
- src/main/java/org/folio/support/UsersApiConstants.java
- src/main/resources/templates/db_scripts/create_blob_table.sql
- src/test/java/org/folio/moduserstest/AbstractRestTest.java
> [MODUSERS-427]- bucket name fix.

- descriptors/ModuleDescriptor-template.json
- ramls/users.raml
The purpose of the PR is to implement MODUSERS-437
As we introduce a new optional field profilePictureLink in user schema, we bump up the minor version of user interface
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> MODUSERS-437 Updating interface version from 16.0 to 16.1

- pom.xml
The purpose of the PR is to implement MODUSERS-441
We have upgraded raml,vertx and other dependencies versions for Quesnelia.
After upgrading vertx and raml module version, docker is not started with below error.
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console..
So to resolve that error, added the below artifact in dependency management which added 2.23 log4j into the classpath
```
<dependency>
<groupId>org.apache.logging.log4j</groupId>
<artifactId>log4j-bom</artifactId>
<version>2.23.0</version>
<type>pom</type>
<scope>import</scope>
</dependency>
```
- Does this PR meet or exceed the expected …
> MODUSERS-441 Upgrading dependencies for Quesnelia

- pom.xml
- ramls/addressTypes.raml
- ramls/departments.raml
- ramls/groups.raml
- ramls/proxiesFor.raml
- ramls/userTenants.raml
- ramls/users.raml
- src/main/java/org/folio/rest/impl/AddressTypeAPI.java
- src/main/java/org/folio/rest/impl/DepartmentsAPI.java
- src/main/java/org/folio/rest/impl/ProxiesForAPI.java
- src/main/java/org/folio/rest/impl/UserGroupAPI.java
- src/main/java/org/folio/rest/impl/UserTenantsAPI.java
- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/test/java/org/folio/rest/impl/AddressTypesApiTests.java
- src/test/java/org/folio/rest/impl/UsersAPITest.java
Upgrade to the latest version of raml-util
> Update to the latest versions of raml-util

- NEWS.md
- pom.xml
Q release
While it's helpful for reviewers to help identify potential problems, ensuring …
> Release q 19.3.1

- src/main/java/org/folio/event/ConsortiumEventType.java
- src/main/resources/templates/db_scripts/schema.json
https://folio-org.atlassian.net/browse/MODUSERS-455 …
> [MODUSERS-455]-Added index for middleName

- src/main/java/org/folio/rest/impl/TenantRefAPI.java
- src/main/resources/sample-data/groups-19.4.0/remote-non-circulating.json
- src/test/java/org/folio/rest/impl/ReferenceAndSampleDataIT.java
- src/test/java/org/folio/rest/impl/ReferenceAndSampleDataMigrationIT.java
https://folio-org.atlassian.net/browse/MODUSERS-456 …
> [MODUSERS-456]-Added patron group Remote Non-circulating

- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/test/java/org/folio/rest/impl/UsersAPIIT.java
purpose of the pr - https://folio-org.atlassian.net/browse/MODUSERS-458
added a validation to make sure that encryption key is not updated.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> MODUSERS-458 making encryption key non updatable

- ramls/userdata.json
- src/test/java/org/folio/rest/impl/UsersAPIIT.java
…user schema
While it's helpful for reviewers to help identify potential problems, ensuring …
> [EDGEPATRON-133]-Schema Fix

- ramls/userdata.json
- src/test/java/org/folio/rest/impl/UsersAPIIT.java
> [MODUSER_ENUM_FIX]-Fixed Enum

- ramls/userdata.json
- src/test/java/org/folio/rest/impl/UsersAPIIT.java
https://folio-org.atlassian.net/browse/MODUSERS-463 …
> MODUSERS-463: fixed PreferredEmailCommunication SERVICE to SERVICES

- src/main/java/org/folio/repository/UserRepository.java
- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/main/java/org/folio/service/event/EntityChangedEventPublisherFactory.java
- src/main/java/org/folio/support/kafka/topic/UsersKafkaTopic.java
- src/test/java/org/folio/moduserstest/GroupIT.java
- src/test/java/org/folio/rest/impl/UsersAPIIT.java
- src/test/java/org/folio/support/kafka/DomainEventAssertions.java
- src/test/java/org/folio/support/kafka/FakeKafkaConsumer.java
Covers: [MODUSERS-451](https://folio-org.atlassian.net/browse/MODUSERS-451)
Use existing domain event pattern implementation to publish users create, update, delete events.
> [MODUSERS-451] Publish domain events for users

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/main/resources/templates/db_scripts/schema.json
> To release 19.3.2

- pom.xml
- src/main/resources/templates/db_scripts/schema.json
https://folio-org.atlassian.net/browse/MODUSERS-473 …
> MODUSERS-473: added staging-users table

- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/staging_userdata.json
- ramls/staging_userdataCollection.json
- ramls/staging_users.raml
- ramls/users.raml
- src/main/java/org/folio/rest/impl/StagingUsersAPI.java
- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/main/java/org/folio/rest/utils/BeanUtils.java
- src/main/java/org/folio/rest/utils/BeanUtilsExtended.java
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/moduserstest/AbstractRestTest.java
- src/test/java/org/folio/rest/InstallUpgradeIT.java
- src/test/java/org/folio/rest/impl/CustomFieldTestBase.java
- src/test/java/org/folio/rest/impl/DepartmentsAPITest.java
- src/test/java/org/folio/rest/impl/StagingUsersAPIIT.java
- src/test/java/org/folio/rest/impl/StagingUsersAPITest.java
- src/test/java/org/folio/rest/impl/UsersAPITest.java
- src/test/java/org/folio/support/http/StagingUsersClient.java
https://folio-org.atlassian.net/browse/MODUSERS-475
https://folio-org.atlassian.net/browse/MODUSERS-474
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> MODUSERS-475: added staging-users CQL Get api with Pagination and POST API

- pom.xml
> MODUSERS-482 - Update RMB version to 35.3.0

- ramls/examples/stagingUserMergeResponse.sample
- ramls/stagingUsersMergeResponse.json
- ramls/staging_users.raml
- src/main/java/org/folio/rest/impl/StagingUsersAPI.java
- src/main/java/org/folio/service/impl/StagingUserService.java
- src/test/java/org/folio/rest/impl/StagingUsersAPIIT.java
The purpose of the PR is to implement MODUSERS-477
Once the user is created/update, the staging user is deleted from staging table. 
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> MODUSERS-477 Deleting staging user once after user is created or updated

- descriptors/ModuleDescriptor-template.json
- pom.xml
> MODUSERS-465 clean up permissions

- .github/workflows/postgres.yml
- pom.xml
> MODUSERS-483 - Updated versions for Ramsons

- NEWS.md
- pom.xml
- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/test/java/org/folio/rest/impl/UsersAPIIT.java
> To release 19.4.1

- NEWS.md
- pom.xml
- src/main/java/org/folio/repository/AbstractRepository.java
- src/main/java/org/folio/repository/UserGroupRepository.java
- src/main/java/org/folio/repository/UserRepository.java
- src/main/java/org/folio/rest/impl/TenantRefAPI.java
- src/main/java/org/folio/rest/impl/UserGroupAPI.java
- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/main/java/org/folio/service/UserGroupService.java
- src/main/java/org/folio/service/event/DomainEvent.java
- src/main/java/org/folio/service/event/DomainEventPublisher.java
- src/main/java/org/folio/service/event/DomainEventType.java
- src/main/java/org/folio/service/event/EntityChangedData.java
- src/main/java/org/folio/service/event/EntityChangedEventFactory.java
- src/main/java/org/folio/service/event/EntityChangedEventPublisher.java
- src/main/java/org/folio/service/event/EntityChangedEventPublisherFactory.java
- src/main/java/org/folio/service/event/FailureHandler.java
- src/main/java/org/folio/support/kafka/topic/UsersKafkaTopic.java
- src/test/java/org/folio/moduserstest/AbstractRestTest.java
- src/test/java/org/folio/moduserstest/GroupIT.java
- src/test/java/org/folio/rest/impl/UsersAPIIT.java
- src/test/java/org/folio/support/VertxModule.java
- src/test/java/org/folio/support/kafka/DomainEventAssertions.java
- src/test/java/org/folio/support/kafka/FakeKafkaConsumer.java
- src/test/java/org/folio/support/matchers/DomainEventAssertions.java
[MODUSERS-489](https://folio-org.atlassian.net/browse/MODUSERS-489)
Bug Fix release, includes ECS TLR feature work
> Bugfix release 19.4.2

- NEWS.md
- pom.xml
- src/main/resources/templates/db_scripts/schema.json
- src/main/resources/templates/db_scripts/update_users_groups_view.sql
- src/test/java/org/folio/rest/impl/UsersAPIIT.java
> To release 19.4.3

- NEWS.md
- pom.xml
- src/main/resources/templates/db_scripts/schema.json
> To release 19.4.4

- ramls/examples/staging_user.sample
- ramls/examples/staging_user_collection.sample
- ramls/staging_userdata.json
- ramls/staging_users.raml
- src/main/java/org/folio/rest/impl/StagingUsersAPI.java
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/impl/StagingUsersAPIIT.java
Generate external system ID and store it in the staging user table. The POST/patron API will be used only for creating and storing the new staging user record. The put operation will be segregated to another API.
Added support for generating and persisting the externalSystemId. Cleaned up the existing POST API call code to be used for only saving the new user creation.
- Do PRs exist for …
> MODUSERS-493 - Changes for the POST /patron for patron registration API

- descriptors/ModuleDescriptor-template.json
- ramls/staging_users.raml
- src/main/java/org/folio/rest/impl/StagingUsersAPI.java
- src/test/java/org/folio/rest/impl/StagingUsersAPIIT.java
- src/test/java/org/folio/support/http/StagingUsersClient.java
> MODUSERS-494 - Added PUT /staging-users/{externalSystemId}

- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/main/java/org/folio/rest/utils/ExpirationTool.java
- src/main/java/org/folio/service/impl/StagingUserService.java
- src/main/java/org/folio/support/StagingUserUpdatesStorage.java
- src/test/java/org/folio/rest/utils/ExpirationToolTest.java
https://folio-org.atlassian.net/browse/MODUSERS-478 …
> MODUSERS-478: published created and updated event after merging staging user and expiration of user 

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/examples/staging_user.sample
- ramls/examples/staging_user_collection.sample
- ramls/staging_userdata.json
- ramls/staging_users.raml
- src/main/java/org/folio/rest/impl/StagingUsersAPI.java
- src/main/java/org/folio/rest/impl/UsersAPI.java
- src/main/java/org/folio/rest/utils/ExpirationTool.java
- src/main/java/org/folio/service/impl/StagingUserService.java
- src/main/java/org/folio/support/StagingUserUpdatesStorage.java
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/impl/StagingUsersAPIIT.java
- src/test/java/org/folio/rest/utils/ExpirationToolTest.java
- src/test/java/org/folio/support/http/StagingUsersClient.java
> To release 19.4.5

- descriptors/ModuleDescriptor-template.json
- ramls/userdata.json
- src/test/java/org/folio/rest/impl/UsersAPIIT.java
- src/test/java/org/folio/support/Personal.java
https://folio-org.atlassian.net/browse/MODUSERS-454 …
> MODUSERS-454: Extended User Record Schema to add Pronouns field

- ramls/userdata.json
- src/test/java/org/folio/moduserstest/AbstractRestTest.java
https://folio-org.atlassian.net/browse/MODUSERS-505 …
> MODUSERS-505: Pronouns field - Add character limit 300

- .github/workflows/postgres.yml
- Dockerfile
- Jenkinsfile
- pom.xml
> FOLIO-4222 - Java and RMB upgrade

- pom.xml
> MODUSERS-508: upgraded folio-custom-fields versions

- NEWS.md
- pom.xml
https://folio-org.atlassian.net/browse/MODUSERS-508 …
> Sunflower release 19.5.0

- pom.xml
> Fix master branch from 19.5.1-SNAPSHOT to 19.6.0-SNAPSHOT

- src/main/java/org/folio/service/impl/StagingUserService.java
- src/test/java/org/folio/rest/impl/StagingUsersAPIIT.java
https://folio-org.atlassian.net/browse/MODUSERS-513 …
> MODUSERS-513: fixed [Users - Patron preregistration] Update expiration date during user record merge

- NEWS.md
- pom.xml
- src/main/java/org/folio/service/impl/StagingUserService.java
- src/test/java/org/folio/rest/impl/StagingUsersAPIIT.java
https://folio-org.atlassian.net/browse/MODUSERS-515 …
> Sunflower release 19.5.1

- NEWS.md
- pom.xml
- src/main/java/org/folio/service/impl/StagingUserService.java
- src/test/java/org/folio/rest/impl/StagingUsersAPIIT.java
Release mod-users (Ramsons CSP #2)
https://folio-org.atlassian.net/browse/MODUSERS-516
While …
> Ramsons release 19.4.6

- NEWS.md
> Post Ramsons release 19.4.6

- pom.xml
https://folio-org.atlassian.net/browse/MODUSERS-521 …
> MODUSERS-521: Upgraded folio-custom-fields with v2.3.1

- src/main/java/org/folio/event/KafkaConfigSingleton.java
Fix spelling of kafka env as introduced in #420
> Fix spelling of env to enable kafka

- src/main/java/org/folio/rest/impl/TenantRefAPI.java
- src/main/java/org/folio/service/event/DomainEventPublisher.java
- src/test/java/org/folio/moduserstest/AbstractRestTest.java
- src/test/java/org/folio/rest/impl/UsersNoKafkaTest.java
Follow-up to MODUSERS-525 . Now with a test :-)
> MODUSERS-526 honor KAFKA_ENABLE in tenant init

- src/main/java/org/folio/service/impl/RecordRepository.java
- src/main/java/org/folio/service/impl/RecordRepositoryImpl.java
- src/main/java/org/folio/service/impl/RecordServiceFactoryImpl.java
- src/main/java/org/folio/service/impl/RecordServiceImpl.java
- src/main/java/org/folio/validate/DisplayInAccordionValidator.java
- src/test/java/org/folio/moduserstest/CustomFieldIT.java
- src/test/java/org/folio/rest/impl/CustomFieldStatisticsTest.java
- src/test/java/org/folio/support/PutCustomFieldsRequest.java
- src/test/java/org/folio/support/http/CustomFieldsClient.java
Jira issue: https://folio-org.atlassian.net/browse/MODUSERS-531
Fix an issue when required for bulk operation method was not implemented
- Use default RecordServiceImpl to perform most of the custom fields operations
- Add missing integration tests to verify bulk update/removal of custom fields
Ideally all of the PRs involved in breaking changes would be …
> MODUSERS-531: Fix bulk removal of custom fields

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- ramls/staging_userdata.json
- src/main/java/org/folio/service/impl/StagingUserService.java
- src/test/java/org/folio/rest/impl/StagingUsersAPIIT.java
To add minor boolean field in post and put API and added corresponding column n staging_user table as per below ticket
https://folio-org.atlassian.net/browse/MODUSERS-533
1. Added boolean minor column in staging_user table.
2. Add or update the user patron group based on minor flag: True: "Basic – Minor (INTERNAL)" and False="Remote Non-circulating"
3. Failing the request if patron groups not found.
4. Incremented staging-users interface minor version.
5. Maintained expiration date logic as per https://folio-org.atlassian.net/browse/MODUSERS-513
https://folio-org.atlassian.net/browse/MODUSERS-533?focusedCommentId=271108
- Does this …
> MODUSERS-533: added minor boolean field in staging_user table and assigned appropriate patronGroup to user record
