ModuleDescriptor.json

Add _tenant interface to `provides` key.
Remove deprecated `tenantInterface` key.

Update ModuleDescriptor.json for Tenant API

---

pom.xml

Use latest aspectj version that contains this fix
https://github.com/mojohaus/aspectj-maven-plugin/issues/18
to make it work in eclipse.

Make aspectj work in eclipse

---

pom.xml

Fixes this warning:
[WARNING] bad version number found in ~\.m2\repository\org\aspectj\aspectjrt\1.8.9\aspectjrt-1.8.9.jar expected 1.8.10 found 1.8.9
aspectj-maven-plugin 1.8.10 matches these versions:
aspectjrt 1.8.9
aspectjtools 1.8.9
http://www.mojohaus.org/aspectj-maven-plugin/usage.html

Fix aspectj version

---

ModuleDescriptor.json
NEWS.md
pom.xml

Kurt, this is a merge of userdata schema changes from modusers-12 and modusers-15, so they can go simultaneously into v11.0.0 without a need for intermediate POM versions. 
Version is set to "11.0.0-SNAPSHOT" - that's what we need when initiating the mvn release process, right. 
"SNAPSHOT" has been removed from the RMB dep.

Modusers 12

---

src/main/resources/templates/db_scripts/schema.json

Search user generates CQL like `query=(((username="cboerema*" or personal.firstName="cboerema*" or personal.lastName="cboerema*" or personal.email="cboerema*" or barcode="cboerema*" or id="cboerema*" or externalSystemId="cboerema*")) and active="true") sortby personal.lastName personal.firstName`. Currently the database schema does not have necessary index to speed up the query. This PR added those necessary indexes. Test in local and see the query time reduced from **1s to 3 ms**.

MODUSERS-106: add indexes to speed up user search

---

src/main/resources/templates/db_scripts/schema.json

In MODUSERS-125, this API call 
```
/users?limit=30&offset=90&query=%28%28username%3D%22gunnarsson%2A%22%20or%20personal.firstName%3D%22gunnarsson%2A%22%20or%20personal.lastName%3D%22gunnarsson%2A%22%20or%20personal.email%3D%22gunnarsson%2A%22%20or%20barcode%3D%22gunnarsson%2A%22%20or%20id%3D%22gunnarsson%2A%22%20or%20externalSystemId%3D%22gunnarsson%2A%22%29%29%20sortby%20active%20patronGroup.group%2Fsort.descending is very slow. 
```
The generated query is like 
```
FROM fs00001000_mod_users.users_groups_view WHERE ((((((lower(f_unaccent(users_groups_view.jsonb->>'username')) ~ lower(f_unaccent('(^|[[:punct:]]|[[:space:]]|(?=[[:punct:]]|[[:space:]]))gunnarsson.*($|[[:punct:]]|[[:space:]]|(?<=[[:punct:]]|[[:space:]]))'))) OR (lower(f_unaccent(users_groups_view.jsonb->'personal'->>'firstNa …
```

MODUSERS-125: add GIN index on id field to improve user search (sort by group) performance

---

src/main/resources/templates/db_scripts/schema.json

Every 30 seconds, mod-users kicks off a query like below. Adding an index on expirationDate field reduces the execution time from about **11.589 ms to 0.218 ms**.
```
WHERE (lower(f_unaccent(users.jsonb->>'active')) LIKE lower(f_unaccent('true'))) AND (users.jsonb->>'expirationDate' <'2019-06-06T16:51:39.827Z')
```

Add index to expirationDate

---

pom.xml
src/main/java/org/folio/rest/impl/UserGroupAPI.java
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/moduserstest/RestVerticleIT.java
src/test/java/org/folio/moduserstest/UserGroupAPITest.java

* Use latest PgUtil.post, PgUtil.getById, PgUtil.deleteById, PgUtil.put where
possible, RMB 26.1.0 has fixed some HTTP status codes.
* Use foreign key users.patronGroup=groups.id
* Extract duplicate unit test code into fail and assertStatus methods.
* Remove postgres-embedded code, this is automatically handled by PostgresClient.

MODUSERS-131: Update to RMB 26.1.0

---

Jenkinsfile

Enables kubeDeploy step on buildMvn pipeline to deploy container to CI kubernetes cluster on release/snapshot builds for FOLIO-2256.

publish container to ci kubernetes when release/snap build

---

.gitignore
src/main/java/org/folio/rest/impl/UsersAPI.java
src/test/java/org/folio/moduserstest/RestVerticleIT.java

Add custom field validation
Refactor post and put user endpoints to allow chaining Future from validateCustomFields with rest of the code in those endpoints.
This PR is difficult to read by looking at changes from the whole PR, so here's explanation for each commit
https://github.com/folio-org/mod-users/pull/138/commits/6a23d68701f6444fa88ca73e2cd4c4766931d633?w=1 - Unwrap code from vertxContext.runOnContext, calling runOnContext is equivalent to running code immediately, see "Learning" section below
https://github.com/folio-org/mod-users/pull/138/commits/3026aeaa60650c85fca831fa74aaa1e56ae8599d?w=1 - replace 
```
try
{...}
catch()
{...} 
```
with
```
Future.succeededFuture()
.compose(...)
.otherwise(...)
```
The second structure also handles thrown exceptions, but it also allows to …

MODUSERS-149: Add custom field validation

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/service/impl/RecordRepository.java
src/main/java/org/folio/service/impl/RecordRepositoryImpl.java
src/main/java/org/folio/service/impl/RecordServiceFactoryImpl.java
src/main/java/org/folio/service/impl/RecordServiceImpl.java
src/main/resources/META-INF/services/org.folio.service.spi.RecordServiceFactory
src/test/java/org/folio/moduserstest/RestVerticleIT.java
src/test/java/org/folio/moduserstest/UserGroupAPITest.java
src/test/java/org/folio/rest/impl/CustomFieldStatisticsTest.java
src/test/java/org/folio/rest/impl/CustomFieldsDBTestUtil.java
src/test/resources/fields/shortTextField.json
src/test/resources/users/user8.json

Per [MODUSERS-153](https://issues.folio.org/browse/MODUSERS-153), calculate custom field usage on User records
- define endpoint to retrieve CF usage statistic: `/custom-fields/{id}/stats`
- introduce `RecordRepository` to implement statistic calculation and CF values removal
- call `RecordRepository` from the implementation of RecordService 
- test the statistic endpoint
- modify existing tests to shutdown vert.x and posgtres in class tear down method 
- update mod-custom-fields dependency to a released version to solve the issue with continues snapshot version updates

MODUSERS-153 Calculate custom field usage on User records

---

Dockerfile
descriptors/ModuleDescriptor-template.json

Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).

MODUSERS-160 FOLIO-2358 manage container memory

---

src/main/resources/templates/db_scripts/schema.json

According to https://github.com/folio-org/raml-module-builder/blob/master/DB-schema-migration.md, 
we need to set custom field "fromModuleVersion" to "mod-users-15.7.0" (the version in which custom fields script was added)

MODCFIELDS-30: Update fromModuleVersion for custom fields script

---

pom.xml
src/main/java/org/folio/rest/impl/UsersAPI.java
src/test/java/org/folio/moduserstest/RestVerticleIT.java

This change expands existing `/users` API to switch to streaming mode automatically when the `limit` parameter is large (200 or above for example). This implementation simplified original POC where new RAML resource type, RAML, API and permissions were proposed. Note, this PR also includes some changes to handle RMB upgrade from v27 to v29. It also uses `RMB 29.2.0-SNAPSHOT` for now since `29.2.0` has not been released.

MODUSERS-114 GET users as a stream

---

pom.xml

Indexes do not get recreated on module upgrade resulting in bad performance.
Update RAML Module Builder (RMB) from 29.2.0 to 29.2.2 to get this fix:
[RMB-550](https://issues.folio.org/browse/RMB-550) Index recreation on module upgrade.
All indexes will be recreated on module upgrade, this may take long. This is needed for
[RMB-498](https://issues.folio.org/browse/RMB-498) and other index changes of 29.2.0.

RMB 29.2.2: Upgrade indexes on module upgrade

---

src/main/java/org/folio/rest/impl/UsersAPI.java

Pass JsonProcessingException to reply handler to return a failure.
Do not swallow the exception stacktrace, log it.
Use English or the tenant language or the language requested by the client, but
not the language of the server.

MODUSERS-114: Log exception including stacktrace for streaming GET Users

---

src/main/java/org/folio/rest/impl/UsersAPI.java
src/test/java/org/folio/moduserstest/RestVerticleIT.java

This reverts [MODUSERS-114](https://issues.folio.org/browse/MODUSERS-114) "GET users as a stream"
There are several issues with the streaming feature:
* [MODUSERS-169](https://issues.folio.org/browse/MODUSERS-169) "User as stream returns 200 on failure"
* [MODUSERS-171](https://issues.folio.org/browse/MODUSERS-171) "wrong totalRecords when streaming GET /users"
This block other work like [MODUSERS-164](https://issues.folio.org/browse/MODUSERS-164) "Upgrade to RMB v29.x"
Therefore the streaming code of MODUSERS-114 should be reverted so that it no longer blocks the master branch. MODUSERS-114 should be developed and code reviewed in a separate pull request on a feature branch, not on master.

MODUSERS-171: wrong totalRecords when streaming GET /users

---

pom.xml
src/main/java/org/folio/rest/impl/ProxiesForAPI.java
src/main/java/org/folio/rest/impl/UsersAPI.java
src/main/java/org/folio/rest/utils/ExpirationTool.java
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/moduserstest/CustomFieldIT.java
src/test/java/org/folio/moduserstest/GroupIT.java
src/test/java/org/folio/moduserstest/RestITSupport.java
src/test/java/org/folio/moduserstest/RestVerticleIT.java
src/test/java/org/folio/rest/impl/ProxiesForAPITest.java
src/test/java/org/folio/rest/impl/UsersAPITest.java
src/test/java/org/folio/rest/utils/ExpirationToolTest.java

Upgrade the code of the module to make it compatible with RMB v29.x and Vertex 3.8.4
Main points:
* replaces the creation and completion of io.vertx.core.Future with Promise
* refactor the tests to substitute usage of HttpClient with WebClient 
* remove all foreign keys fields and the primary key field id from the all index sections
Additionally move part of the tests out of RestVerticleIT to group them by subjects
* user groups related tests to GroupIT
* custom fields related test to CustomFieldIT
Note: for some reason WebClient doesn't want to work with data retrieved from stream (see UsersAPI.getUsers()). Without streamin it works ok.  So I had to revert code back [(5a3af74)](https://github.com/folio-org/mod-users/pull/154/commits/5a3af74dc7f851374ffecbd79830d72c332706c6) to HttpClient …

MODUSERS-164  Upgrade to RMB v29.x

---

src/main/java/org/folio/service/impl/RecordRepository.java
src/main/java/org/folio/service/impl/RecordRepositoryImpl.java
src/main/java/org/folio/service/impl/RecordServiceImpl.java
src/main/resources/vertx-default-jul-logging.properties
src/test/java/org/folio/rest/impl/CustomFieldRemovalTest.java
src/test/java/org/folio/rest/impl/CustomFieldStatisticsTest.java
src/test/resources/fields/singleCheckbox.json
src/test/resources/users/user9.json

According to [MODUSERS-172](https://issues.folio.org/browse/MODUSERS-172) implement cascade removal of custom field values when the custom field is removed. 
The existing `DELETE /custom-fields/<id>` operation for custom field is extended with ability to remove related values from all the records.

MODUSERS-172 Remove related values when custom field is being deleted

---

src/main/java/org/folio/rest/impl/UserGroupAPI.java
src/test/java/org/folio/moduserstest/GroupIT.java

**Purpose**
When a patron group is deleted, delete all patron block limits assosiated with it.
This PR resolves [MODUSERS-180](https://issues.folio.org/browse/MODUSERS-180).

[MODUSERS-180] Maintain Patron Blocks Limits Table entries: patron group deletion

---

ramls/userdata.json
src/test/java/org/folio/moduserstest/GroupIT.java

Not a problem in RMB, but because, for some reason, id is required
in the JSON schema.

Fix ID is mandatory when POSTing a new user MODUSERS-187

---

pom.xml

The changes for MODUSERS-193 included removing provision of the
`patron-block-conditions` and `patron-block-limits` interfaces and MODUSERS-201 included an incompatible change to the `custom-fields` interface. 
These are considered incompatible with the last release and hence the major version should change.

Change version to 17.0.0 MODUSERS-197 MODUSERS-193

---

src/main/java/org/folio/rest/utils/ExpirationTool.java
src/test/java/org/folio/moduserstest/GroupIT.java
src/test/java/org/folio/rest/utils/ExpirationToolTest.java

`nspname LIKE '%_mod_users'`
matches diku_my_mod_users and diku_modmusers.
This is wrong.
Use `nspname ~ '^[^_]+_mod_users$'` instead.
Errors are logged using logger.info. Use logger.error instead.
Log tenant.
Remove unused Context parameter.

MODUSERS-221: Fix ExpirationTool nspname LIKE and error logging

---

pom.xml

This may fix https://issues.folio.org/browse/MODUSERS-213 "current transaction is aborted".
Release notes: https://github.com/vert-x3/wiki/wiki/3.9.3-Release-Notes#vertx-sql-client
They mention several fixes regarding prepared statements and RowStream, most notably:
https://github.com/eclipse-vertx/vertx-sql-client/issues/730 RowStream implementation fixes:
The implementation of RowStream does not manage correctly its state (e.g it is not reentrant)
and **does not close the cursor** when it is not needed anymore.

MODUSERS-224: Upgrade vert.x from 3.9.2 to 3.9.3

---

src/main/resources/sample-data/README.md
src/main/resources/sample-data/users/User046.json
src/main/resources/sample-data/users/User300.json
src/main/resources/sample-data/users/User301.json
src/main/resources/sample-data/users/User302.json
src/test/java/org/folio/rest/impl/UsersAPIIT.java

https://samltest.id/ runs a test IdP for Single-Sign-On (SSO)
that FOLIO demo and test installations may use. It provides
3 demo users that should be added to the mod-users sample users
for ease of deployment. These are the usernames and passwords:
rick psych
morty panic
sheldon bazinga

MODUSERS-227: Sample users for SSO login using samltest.id

---

pom.xml

https://issues.folio.org/browse/MODUSERS-230 - Upgrade to RAML Module Builder 31.1.2.
* Upgrade to the RMB 31.1.2;
* Vert.x 3.9.3 is already used.
* Add `Multi-Release` to prevent `WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.`
Tested on the team scratch env - following query `{{host}}/users?limit=150` return 150 users as expected.

MODUSERS-230: Upgrade to RMB v31.1.2.

---

pom.xml

Release notes: https://github.com/vert-x3/wiki/wiki/3.9.4-Release-Notes
Most notable fix:
* RowStream fetch can close prematurely the stream
https://github.com/eclipse-vertx/vertx-sql-client/issues/778

MODUSERS-233: Upgrade vert.x from 3.9.3 to 3.9.4

---

pom.xml

RMB 31.1.3 contains:
* [RMB-740](https://issues.folio.org/browse/RMB-740) Use FOLIO fork of vertx-sql-client and vertx-pg-client with
the following two patches
* [RMB-739](https://issues.folio.org/browse/RMB-739) Make RMB's DB\_CONNECTIONRELEASEDELAY work again, defaults to 60 seconds
* [FOLIO-2840](https://issues.folio.org/browse/FOLIO-2840) Fix duplicate names causing 'prepared statement "XYZ" already exists'

MODUSERS-236: Upgrade RMB to 31.1.3

---

NEWS.md
pom.xml

* [MODUSERS-235](https://issues.folio.org/browse/MODUSERS-235) Upgrade RMB to 30.2.9 and Vert.x to 3.9.4:
* [RMB-740](https://issues.folio.org/browse/RMB-740) Use FOLIO fork of vertx-sql-client and vertx-pg-client with
the following two patches
* [RMB-739](https://issues.folio.org/browse/RMB-739) Make RMB's DB\_CONNECTIONRELEASEDELAY work again, defaults to 60 seconds
* [FOLIO-2840](https://issues.folio.org/browse/FOLIO-2840) Fix duplicate names causing 'prepared statement "XYZ" already exists'
* [RMB-738](https://issues.folio.org/browse/RMB-738) Upgrade to Vert.x 3.9.4, most notable fix: RowStream fetch
can close prematurely the stream https://github.com/eclipse-vertx/vertx-sql-client/issues/778

MODUSERS-235: Release 17.1.2 with RMB to 30.2.9 and Vert.x 3.9.4

---

descriptors/ModuleDescriptor-template.json
ramls/examples/group.sample
ramls/examples/groups.sample
ramls/groups.raml
ramls/usergroup.json
reference-data/groups/faculty.json
reference-data/groups/staff.json
src/test/java/org/folio/moduserstest/GroupIT.java

Refs https://issues.folio.org/browse/MODUSERS-234
In order to implement [UIU-1908](https://issues.folio.org/browse/UIU-1908) we need a property describing the default expiration offset in days for a patron group.
This PR adds the optional property _expirationOffset_ to the _usergroup_ schema.

MODUSERS-234: Add property expiration offset to usergroup

---

pom.xml

RMB 31.1.5 provides
* RMB-750 Change lock for "tuple concurrently updated" when upgrading Q2 to Q3 (REVOKE)
RMB 31.1.4 provides
* RMB-744 fix "tuple concurrently updated" when upgrading Q2 to Q3 (REVOKE)
The FOLIO fork of vertx-sql-client and vertx-pg-client provides
* RMB-739 Make RMB's DB_CONNECTIONRELEASEDELAY work again, defaults to 60 seconds
* FOLIO-2840 Fix duplicate names causing 'prepared statement "XYZ" already exists'

MODUSERS-237: Upgrade to RMB 31.1.5

---

NEWS.md
pom.xml
src/main/java/org/folio/rest/impl/UsersAPI.java
src/test/java/org/folio/moduserstest/CustomFieldIT.java
src/test/java/org/folio/moduserstest/GroupIT.java
src/test/java/org/folio/moduserstest/RestVerticleIT.java
src/test/java/org/folio/moduserstest/UserGroupAPITest.java
src/test/java/org/folio/rest/impl/CustomFieldTestBase.java
src/test/java/org/folio/rest/impl/UsersAPIIT.java
src/test/java/org/folio/rest/utils/ExpirationToolTest.java

The custom fields tests needed to be changed as during the upgrade of `folio-custom-fields` to RMB 33.0.0 there was also a change from using the `X-Okapi-Token` header to the `X-Okapi-User-Id` header to determine which user created the custom field. 
If this header is not present, the process to find the users fails reporting a 401 (this is not a response from the self-referential API request, rather a fake response when the header is not provided or blank).
There is also a change to the configuration of the AspectJ plugin in order to improve the reliability of the departments tests (yes, this probably should be a separate pull request)

Upgrade to RAML Module Builder 33.0.0 MODUSERS-255

---

pom.xml

While trying to build the release, got a warning the pomfile
had two entries for the same plugin, and this could cause 
instability and might cause build failures in future.  Checked 
the pomfile and this did seem to be the case, so I consolidated 
the two entries.  Re-ran tests to make sure this didn't break anything.

consolidating plugin entries

---

src/main/java/org/folio/rest/impl/UsersAPI.java

https://dev.folio.org/guidelines/contributing/#style-conventions
suggests:
We indent with two spaces only, because vert.x uses deeply nested callbacks.
This changes the line wrap indentation suggested by Sun Java Code style from 8 spaces to 4 spaces because line wrapping uses two indentation levels:
https://www.oracle.com/java/technologies/javase/codeconventions-indentation.html
4 spaces also complies with Google Java Style Guide: https://google.github.io/styleguide/javaguide.html#s4.5.2-line-wrapping-indent

MODUSERS-264: Fix indentation of UsersAPI.java

---

src/main/java/org/folio/rest/impl/AddressTypeAPI.java
src/main/java/org/folio/rest/impl/DepartmentsAPI.java
src/main/java/org/folio/rest/impl/ProxiesForAPI.java
src/main/java/org/folio/rest/impl/TenantRefAPI.java
src/main/java/org/folio/rest/impl/UserGroupAPI.java
src/main/java/org/folio/rest/impl/UsersAPI.java
src/main/java/org/folio/service/impl/RecordRepositoryImpl.java
src/test/java/org/folio/moduserstest/GroupIT.java
src/test/java/org/folio/moduserstest/RestITSupport.java
src/test/java/org/folio/moduserstest/RestVerticleIT.java

If the parameter list of a method is broken into multiple lines indent by 4 spaces and put an empty line after the parameter list.
Requested on https://github.com/folio-org/mod-users/pull/207
This complies with
* https://google.github.io/styleguide/javaguide.html#s4.5.2-line-wrapping-indent and
* https://www.oracle.com/java/technologies/javase/codeconventions-indentation.html#248 and
* https://dev.folio.org/guidelines/contributing/#consistent-whitespace

MODUSERS-265: Reformat methods with multi-line parameter list

---

src/test/java/org/folio/rest/impl/UsersAPIIT.java

Requested on https://github.com/folio-org/mod-users/pull/207
Exceptions: "static" is only allowed if the method is currently called by a static method.

MODUSERS-266: Remove "static" from all helper methods in UsersAPIIT

---

NEWS.md
pom.xml

RMB 33.1.1 is needed to fix the database memory fix RMB-863. mod-users is affected because it uses PgUtil.streamGet: https://github.com/folio-org/mod-users/blob/v18.1.0/src/main/java/org/folio/rest/impl/UsersAPI.java#L149
Also update folio-service-tools.version to 1.7.1 and
folio-custom-fields.version to 1.6.1
for Vert.x 4.1.4 support.
Also update joda-time from 2.10.6 to 2.10.12 and some test dependencies.

MODUSERS-272: Update RMB to 33.1.1 and Vert.x to 4.1.4

---

NEWS.md
pom.xml

Resolve CVE-2021-44228 as per [MODUSERS-295](https://issues.folio.org/browse/MODUSERS-295).

MODUSERS-295: Upgrade to RMB 33.1.3 and Folio Service Tools 1.7.2 (Kiwi R3 2021).

---

NEWS.md
pom.xml

Resolve CVE-2021-44228 as per [MODUSERS-297](https://issues.folio.org/browse/MODUSERS-297).

MODUSERS-297: Upgrade to RMB 33.1.3 and Folio Service Tools 1.7.2 (Juniper R2 2021).

---

NEWS.md
pom.xml

Resolve CVE-2021-44228 as per [MODUSERS-295](https://issues.folio.org/browse/MODUSERS-295).

MODUSERS-295: Upgrade to RMB 33.1.3 and Folio Service Tools 1.7.2 (Lotus)

---

pom.xml
src/test/java/org/folio/moduserstest/RestVerticleIT.java

https://www.joda.org/joda-time/ suggests:
"Note that from Java SE 8 onwards, users are asked to migrate to java.time (JSR-310) - a core part of the JDK which replaces this project."
mod-users has a runtime dependency on joda, however, it uses joda in tests only.
Therefore this commit replaces joda by java.time in tests and completely removes joda dependency from pom.xml.

MODUSERS-305: Drop joda, replace by java.time

---

pom.xml
src/test/java/org/folio/moduserstest/GroupIT.java
src/test/java/org/folio/support/Address.java
src/test/java/org/folio/support/Group.java
src/test/java/org/folio/support/Groups.java
src/test/java/org/folio/support/User.java
src/test/java/org/folio/support/Users.java
src/test/java/org/folio/support/ValidationError.java
src/test/java/org/folio/support/ValidationErrors.java
src/test/java/org/folio/support/http/GroupsClient.java
src/test/java/org/folio/support/http/OkapiHeaders.java
src/test/java/org/folio/support/http/UsersClient.java

*Purpose*
Reduce the number of [reported code smells](https://sonarcloud.io/project/issues?resolved=false&id=org.folio%3Amod-users)
*Approach*
* Use hamcrest for assertions (instead of vert.x context)
* Use vert.x junit 5.0 integration for groups integration test
* Use rest assured for making requests to the APIs
* Introduce classes for easier creation / inspection of JSON representations of users and groups
* Split up the existing test in individual tests (to reduce complexity and improve feedback)
* Extract use of rest assured to separate client classes
*TODO*
* Move the tests relating to users to the users integration tests (requires improvement to that test class first)
* Reduce complexity of rest verticle integration tests by splitting examples into separate tests

Improve groups integration test complexity MODUSERS-309

---

src/test/java/org/folio/moduserstest/ExpirationIT.java
src/test/java/org/folio/moduserstest/GroupIT.java
src/test/java/org/folio/moduserstest/ProxyRelationshipsIT.java
src/test/java/org/folio/rest/impl/AddressTypesIT.java
src/test/java/org/folio/rest/impl/PatronPinAPIIT.java
src/test/java/org/folio/rest/impl/ReferenceAndSampleDataIT.java
src/test/java/org/folio/rest/impl/UsersAPIIT.java
src/test/java/org/folio/support/http/AddressTypesClient.java
src/test/java/org/folio/support/http/ExpirationClient.java
src/test/java/org/folio/support/http/GroupsClient.java
src/test/java/org/folio/support/http/OkapiHeaders.java
src/test/java/org/folio/support/http/OkapiUrl.java
src/test/java/org/folio/support/http/PatronPinClient.java
src/test/java/org/folio/support/http/ProxiesClient.java
src/test/java/org/folio/support/http/RestAssuredClient.java
src/test/java/org/folio/support/http/RestAssuredCollectionApiClient.java
src/test/java/org/folio/support/http/RestAssuredConfiguration.java
src/test/java/org/folio/support/http/UsersClient.java

*Purpose*
* Remove duplication of code that uses RestAssured to interact with a record collection API.
*Approach*
* Introduce a new class to consolidate the use of RestAssured to
* Move behaviour to the new record collection client class
* Use new client in existing clients that use rest assured
* Extract a configuration class to allow the common specification and config for RestAssured to be used by non record collection API clients

Consolidate rest assured usage MODUSERS-309

---

src/main/java/org/folio/rest/impl/ProxiesForAPI.java
src/main/java/org/folio/rest/impl/UsersAPI.java
src/main/java/org/folio/rest/utils/ExpirationTool.java
src/test/java/org/folio/rest/impl/ProxiesForAPITest.java
src/test/java/org/folio/rest/impl/UsersAPITest.java
src/test/java/org/folio/rest/utils/ExpirationToolTest.java

*Purpose*
Removing warnings related to the use of argument capture. The warnings are irritating and the approach makes the tests harder to follow as the arrangement of these expectations are done _after_ the production code is executed.
As part of this work I discovered that there were _no tests_ for successful expiration of users.
*Approach*
* Add integration tests for disabling expired users
* Change the existing tests to use `doAnswer` in order to arrange expectations prior to execution
* Change the existing tests and production code to use future rather than handler based methods from PostgresClient

Remove argument captor MODUSERS-317

---

NEWS.md
pom.xml
ramls/userdata.json
ramls/users.raml
src/test/java/org/folio/rest/impl/UsersAPIIT.java

I was not sure if I needed to increment the interface version a full number as well.
The api now seems to issue a 422 error when an addressTypeId is not provided.
I'm not sure if that's correct-shouldn't it be a 400 error?

MODUSERS-212: Make AddressTypeID field required for addresses

---

src/test/java/org/folio/moduserstest/CustomFieldIT.java
src/test/java/org/folio/moduserstest/ExpirationIT.java
src/test/java/org/folio/moduserstest/GroupIT.java
src/test/java/org/folio/moduserstest/ProxyRelationshipsIT.java
src/test/java/org/folio/rest/impl/AddressTypesIT.java
src/test/java/org/folio/rest/impl/ReferenceAndSampleDataIT.java
src/test/java/org/folio/rest/impl/UsersAPIIT.java

Locally I always get
```
[ERROR]   ReferenceAndSampleDataIT.manySampleUsersAreCreated:84
Expected: is <303>
but: was <305>
```
when doing `mvn install`.
The two unexpected users have been created by some other test.
Solution:
Use a different tenant for each integration test to make them independent.

MODUSERS-324: Don't reuse tenant in integration tests

---

pom.xml

Upgrade vertx from 4.3.1 to 4.3.3 fixing disabled SSL: https://github.com/vert-x3/wiki/wiki/4.3.2-Release-Notes
Upgrade RMB from 34.0.0 to 34.0.2 to match the new Vert.x version.
Upgrade folio-service-tools from 1.7.0 to 1.8.0 to match the new RMB version.
Upgrade folio-custom-fields from 1.8.0 to 1.9.0, this upgrades spring-beans, spring-expression and spring-context from 5.3.16 to 5.3.20 fixing Denial of Service (DoS) https://nvd.nist.gov/vuln/detail/CVE-2022-22970 , https://nvd.nist.gov/vuln/detail/CVE-2022-22950 , and Improper Handling of Case Sensitivity https://nvd.nist.gov/vuln/detail/CVE-2022-22968

MODUSERS-326: Vert.x 4.3.3, Spring 5.4.20 fixing vulnerabilities

---

src/test/java/org/folio/rest/impl/AddressTypesIT.java

"LANG=de_DE.UTF-8 mvn install" fails with
```
[ERROR]   AddressTypesIT.cannotCreateAnAddressTypeWithoutAName:99
Expected: is "must not be null"
but: was "darf nicht null sein"
```
Fix: Rewrite the test without using the translated message.

MODUSERS-325: AddressTypesIT fails when locale is not English

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rest/impl/UsersAPI.java

I neglected to increment the version number in the descriptor file.
Edit:  I've also removed the check for a null addresstypeId, as this is not needed,  but I have
left other address-related checks in place, as they check for uniqueness and that the id
provided actually exists in the system.

MODUSERS-212: Make addresstypeid property required for addresses

---

NEWS.md
ramls/users.raml
src/main/java/org/folio/rest/impl/UsersAPI.java
src/test/java/org/folio/rest/impl/UsersAPIIT.java
src/test/java/org/folio/rest/impl/UsersAPITest.java

[UIU-1562](https://issues.folio.org/browse/UIU-1562) removed the need for a count of users by patron group from the UI (as the current implementation was not fit for purpose).
In order to reduce the maintenance burden, the facets functionality can be removed from mod-users.
* Remove the user facets API
* Increment major version of `users` interface (as this is an breaking change)
* Increment module major version (as this is an breaking change)
* Stop loading sample records during users API integration test (as tests no longer rely on them)

Remove user facets API MODUSERS-308

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml
Jenkinsfile
README.md
ramls/groups.raml

[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).

FOLIO-3678 MODUSERS-343 Use GitHub Workflows api-lint and api-schema-lint and api-doc

---

ramls/userEvent.json
src/main/java/org/folio/event/service/UserEventProducer.java
src/test/java/org/folio/rest/impl/UsersAPIIT.java

- Updated the userEvent.json RAML file to include the tenantId property, which represents the name of the user's tenant.
- Refactored the userSnapshot property to userDto for consistency and improved readability.
- Refactored the sendUserCreatedEvent method to accept the tenantId as a parameter in addition to the user and eventAction parameters.
- Updated the getUserEvent method to include the tenantId in the UserEvent object.
- Removed redundant code related to setting userId, actionDate, and user properties based on eventAction.

[MODUSERS-347] - Implement sending USER_CREATED event using transactional outbox pattern

---

descriptors/ModuleDescriptor-template.json
ramls/userTenants.raml
src/main/java/org/folio/rest/impl/UserTenantsAPI.java
src/test/java/org/folio/rest/impl/UserTenantIT.java
src/test/java/org/folio/support/http/UserTenantClient.java

Resolves [MODUSERS-364](https://issues.folio.org/browse/MODUSERS-364) Create Post user-tenant endpoint
We need this for new approach in mod-authtoken
- After adding some institutional tenant to Consortium mod-consortia will invoke POST endpoint implemented here to create some dummy user tenant record
- Mod-authtoken will call GET /user-tenant endpoint in the institutional tenant to check totalRecords(in case when tenant in header not matches with tenant in token). If totalRecords > 0 - mod-authtoken will allow the cross-tenant request

[MODUSERS-364] Create Post user-tenant endpoint

---

ramls/department.json
ramls/examples/department.sample
ramls/examples/departmentCollection.sample
ramls/examples/group.sample
ramls/examples/groups.sample
ramls/usergroup.json

Resolves: [MODCON-66](https://issues.folio.org/browse/MODUSERS-370) Modify users dtos to include source field.
This table describes what setting we are going to implement in Consortium Manager:
https://wiki.folio.org/display/FOLIJET/Consortium+manager+settings
So for _mod-users_ it is _departments_ and _patron groups_.
Setting created in Consortium Manager will have value 'Consortium' and we will add validation to prevent updating them

[MODUSERS-370] Modify users dtos to include source field

---

ramls/userTenants.raml
src/main/java/org/folio/rest/impl/UserTenantsAPI.java
src/test/java/org/folio/rest/impl/UserTenantIT.java

[MODUSERBL-169](https://issues.folio.org/browse/MODUSERBL-169)
Before this change /user-tenant endpoint filters by username, userId, ematil etc only using AND operator.
For Forgot password/Forgot username we need to search by mutiple fields using OR operator and we introduced new param to specify operator for filtering. AND is by default

[MODUSERBL-169] - getUserTenants criterion changed to or

---

src/main/java/org/folio/repository/UserTenantRepository.java
src/main/java/org/folio/rest/impl/UserTenantsAPI.java
src/main/resources/templates/db_scripts/create_user_tenants_table.sql
src/main/resources/templates/db_scripts/update_user_tenants_table.sql
src/test/java/org/folio/rest/impl/UserTenantIT.java

Fix case sensitivity issue with the "username" field on the "Log in" page for "member" users in the "Consortia" environment. Ensure successful login regardless of username letter case.
- Index for username column was updated.  Indexing is now functional using the LOWER PG function.
- Username field will be compared only in lower case when fetching user-tenants.
[MODUSERS-376](https://issues.folio.org/browse/MODUSERS-376)
- Are the …

[MODUSERS-376] - "Username" field on "Log in" page is case-sensitive for "member" user on "Consortia" environment

---

pom.xml

Platform complete version for mod-users contains already released version
https://github.com/folio-org/platform-complete/blob/snapshot/install.json#L101 19.2.1 that ovverides the latest snapshot version.
The latest snapshot version always should contain higher version that latest release version

Use correct snapshot version for next release

---

src/main/resources/templates/db_scripts/schema.json

https://issues.folio.org/browse/MODUSERS-426
A database trigger for `custom_fields` table was updated to not set any metadata values to `"undefined"` (see [FCFIELDS-47](https://issues.folio.org/browse/FCFIELDS-47) and [PR#44](https://github.com/folio-org/folio-custom-fields/pull/44)). To ensure no such values are present after module upgrade the provided migration script needs to run.
Updated `schema.json`.

[MODUSERS-426] Add migration script for custom fields

---

pom.xml

https://folio-org.atlassian.net/browse/MODUSERS-446
mod-users has the com.amazonaws:aws-java-sdk dependency.
This dependency is not needed.
This dependency increases the size of mod-users-fat.jar from 67 MB to 351 MB.
Solution: Removing the dependency.

MODUSERS-446: Remove aws-java-sdk

---

src/main/resources/templates/db_scripts/schema.json
src/main/resources/templates/db_scripts/update_users_groups_view.sql
src/test/java/org/folio/rest/impl/UsersAPIIT.java

The problem arises when sorting is implemented on the PatronGroup column subsequent to applying the filter Active = true. Both the filter query (Active = true) and the sorting operation on PatronGroup seem to be interacting problematically. The filter queries the user table, whereas sorting on PatronGroup accesses the users_groups_view. Notably, some user records do not appear in the users_groups_view. This issue occurs because, as observed in the snapshot, the userGroup for some users' patron groups is not set, hence those records are missing from the users_groups_view, resulting in a reduced result set.
Made changes in the users_groups_view to use left join instead of an inner join between users and groups table to have users with/without patronGroup 
Before merging this PR, please go …

MODUSERS-486 - Sorting users by patron group with applied filters changes number of found records

---

src/main/java/org/folio/event/service/UserOutboxService.java
src/test/java/org/folio/rest/impl/UsersAPIConsortiaTest.java

[[MODCONSKC-61] ECS | Update Member tenant user email value on Central tenant](https://folio-org.atlassian.net/browse/MODCONSKC-61)
- Check email updates for personal data change when sending event to outbox

[MODCONSKC-61] ECS | Update Member tenant user email value on Central tenant

---

src/main/java/org/folio/rest/impl/UsersAPI.java
src/main/java/org/folio/service/event/DomainEventPublisher.java

https://folio-org.atlassian.net/browse/MODUSERS-507
- Shadow users are copies of real staff users, skip sending update events for them
- Remove user info from logs
- Close kafka producers to avoid memory leaks

MODUSERS-507. Staff User created in member tenant becomes as Shadow after updating email, firstname

---

ramls/userTenants.raml
src/main/java/org/folio/event/service/UserTenantService.java
src/main/java/org/folio/repository/UserTenantRepository.java
src/main/java/org/folio/rest/impl/UserTenantsAPI.java
src/test/java/org/folio/rest/impl/UserTenantIT.java
src/test/java/org/folio/support/http/UserTenantClient.java

[[MODCONSKC-69] Add support for deleting related module's data for consortia tenant hard delete](https://folio-org.atlassian.net/browse/MODCONSKC-69)
Extend user tenants endpoint with a new param `tenantId` to differentiate deleting records from member or central user_tenants table

[MODCONSKC-69] Add support for deleting related module's data for consortia tenant hard delete

---

.vscode/settings.json
README.md
pom.xml

Fixes mvn reporting:
```
dependencies.dependency.scope' for org.testcontainers:testcontainers-bom:pom must
be one of [provided, compile, runtime, test, system] but is 'import'. @ line 139, column 14
```
Specify java 21 and current year README.
The double import was introduced in commit 46b4ae38c199b11fcf8c2e84015a911e962b09a8

MODUSERS-524 double import of testcontainers-bom
